# Welcome to Jekyll!

title: Duc-Viet Hoang's notes
author:
  name: ducviet00
  email: vietyb00@gmail.com
description: >-
  A collection of my notes, experiments, and thoughts — a place to learn in public.
baseurl: ""
url: "https://notes.ducviet00.github.io"

highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

remote_theme: jekyll/minima

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji

google_analytics: G-L3M6RV8LN0

minima:
  skin: gruvbox
  
  nav_pages:
    - about.markdown

  social_links:
    - title: ducviet00
      icon: github
      url: "https://github.com/ducviet00/"
    - title: Duc-Viet Hoang
      icon: linkedin
      url: "https://www.linkedin.com/in/ducviet00/"

  show_excerpts: false
  hide_site_feed_link:: true
